// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDta4uzwFZ8Nz69_1aRVkkuB53StKXyhso',
    appId: '1:291678775965:web:353763a7630600db2c8274',
    messagingSenderId: '291678775965',
    projectId: 'igrocery-f0241',
    authDomain: 'igrocery-f0241.firebaseapp.com',
    storageBucket: 'igrocery-f0241.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZnPDKbYnSk1oP_EZHaFuNd5oJxtFAHuw',
    appId: '1:291678775965:android:bb9be60c511262482c8274',
    messagingSenderId: '291678775965',
    projectId: 'igrocery-f0241',
    storageBucket: 'igrocery-f0241.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4rSUwkNOnvpjzlvElXwkfqHXlL3dscHI',
    appId: '1:291678775965:ios:4af1c1eb68ec0f112c8274',
    messagingSenderId: '291678775965',
    projectId: 'igrocery-f0241',
    storageBucket: 'igrocery-f0241.appspot.com',
    iosBundleId: 'com.ibmf.iGrocery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4rSUwkNOnvpjzlvElXwkfqHXlL3dscHI',
    appId: '1:291678775965:ios:5644acf47e38fb3c2c8274',
    messagingSenderId: '291678775965',
    projectId: 'igrocery-f0241',
    storageBucket: 'igrocery-f0241.appspot.com',
    iosBundleId: 'com.ibmf.iGrocery.RunnerTests',
  );
}
